getoutreach/jsonnet-libs

concourse/templates.libsonnet

Fix error for go version of jsonnet `Positional argument after a named argument is not allowed`

fix for go version of jsonnet

---

kubernetes/kube.libsonnet

Phase 1, which blocks this PR is [here](https://github.com/getoutreach/kube_factory/pull/328).
- Manually GC legacy VPAs, checkpoints, and CRDs
- Deploy new VPAs + Scale all 3 VPA components back up

VPA: v1alpha1 (0.2) -> v1beta1 (0.3)

---

kubernetes/cluster.libsonnet
kubernetes/outreach.libsonnet
kubernetes/prom.libsonnet

* Add to `PrometheusRule` to `prom.libsonnet`
* Move `cluster` to it's own file to deprecate key usage

Add PrometheusRule resource

---

kubernetes/kube.libsonnet

Specifically to address this issue with server-experimental mentioned here:  https://outreach-hq.slack.com/archives/C9JBBS0MD/p1564846497351900
But generally, this allows patterns where we might want `app` to be the same for multiple deployments (to be part of the same service, for example), but we want the pdb to be independent.

Use name rather than app for pdb selector

---

concourse/resources.libsonnet

This switches us to use the global fqdn instead of the cluster local fqdn.

[PLAT-2001] use global vault fqdn

---

concourse/templates.libsonnet

**What this PR does**: Adds `on_success` and `on_failure` plumbing for the k8s-deploy-resource template.

DEVTOOL-102: feat(concourse): add plumbing of on_success/failure

---

concourse/pipeline.libsonnet
concourse/resources.libsonnet

Move the maestro boilerplate stuff to the BasicResources section of the library to make adoption easier.

DEVTOOL-93 Add maestro to basic resources

---

concourse/helpers.libsonnet
concourse/pipeline.libsonnet
concourse/templates.libsonnet

This adds 2 things:
1. A set of functions for basic slack messages (deployment start, deployment successful, deployment failed) to make those single lines in a pipeline.jsonnet file.  We seem to be using the same block of code for these most of the time, so I just used that.
2. A set of arrays containing basic kv pairs for bentos and clusters.  This _might_ be assuming too much (in which case we just not use them), but it seems helpful for microservices whose configuration only differs by properties inherent to the cluster/bento it's being deployed to.  If that proves to be untrue in most cases, we can drop this, but signs point to it being useful.

Add helpers and slack message functions

---

kubernetes/kube.libsonnet

https://outreach-io.atlassian.net/browse/PLAT-2433
This is the definition update for vertical-pod-autoscalers to reduce the enormous amount of error logs being generated because we're targeting pods on the deprecated `matchLabel` rather than `targetRef`.
The spec change is required to upgrade VPA: https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.5.0
I believe I am going to have to open PRs to give each VPA a `target`, and so this PR may be the first of many.

PLAT-2433 Migrate VPA spec definition to use API v1beta2

---

kubernetes/argo.libsonnet

This file is functionally identical to https://github.com/getoutreach/argo-flagship/blob/master/k8s/argo.libsonnet and is added here so that we can use them more widely.  I expect this might be more in flux (in the near future anyway) than the otherwise very stable kube.libsonnet, hence keeping it in its own separate file.

Move argo libs here for general use

---

kubernetes/kube.libsonnet

ClusterRoleBinding objects don't require a namespace, so rather than forcing `namespace: null` on objects, lets just check if its set or not.

Let namespace be null

---

concourse/templates.libsonnet

This removes the `version: every` argument for the PR resource. With the new re-run with same inputs button it removes the need to have a way to trigger on every version.
Current behavior causes some pipelines to hang on already merged PRs, specifically the `proxysql` repo is running tests against the incorrect PR. This fix was tested and resulted in the appropriate behavior.

FIX: remove version:every

---

kubernetes/argo.libsonnet

Uses the new images built in argo-docker when making argo resources with the library functions.

Use new argo images in library

---

kubernetes/outreach.libsonnet

This prepares us for an upgrade for cert-manager in the future. We're going to need to migrate to the new annotations.
Source: https://cert-manager.io/docs/installation/upgrading/upgrading-0.10-0.11/

feat/new annotations for cert-manager

---

concourse/helpers.libsonnet

This change removes the staging2 & staging.us-west-2 references from
these here helpers as we are removing both staging2 & staging.us-west-2
from our infrastructure.
NOTE: Please do not merge until the staging2 decom has begun.

Remove staging2 & staging.us-west-2 references from helpers

---

concourse/templates.libsonnet

Manually tested this in a pipeline and confirmed that it checks out the specified version and that overwriting the source works as intended.

Add checkoutMaestroVersion function for pipelines

---

concourse/resources.libsonnet

All of these have been moved with the appropriate tags to gcr.  Note that all pipelines using these images (which is to say, all pipelines) will need to be reapplied to pick up the changes.

DEVTOOL-576: Moving the last of the basic resource images to gcr

---

kubernetes/kube.libsonnet

This is part of upgrading the vertical pod autoscaler components.

fix: remove selector from VPA definition

---

concourse/pipeline.libsonnet
concourse/resources.libsonnet

**What this PR does**: This PR adds support to our concourse `source` resource to allow configuring the base branch, this allows us to continue support repositories with a `main` branch.

feat(concourse): allow overriding the head branch

---

concourse/templates.libsonnet

Removing the cache path for the image build path disables caching (see the resource code here: https://github.com/vito/oci-build-task).  I'm doing this at the library level because:
- We shouldn't be building anything in concourse other than `outreach-docker` anyway
- Setting this in the library and then unsetting it for all of those tasks seems dumb
- Any builds we do want to make sure that we get the latest version of everything anyway, since this is how we handle patches.  If we use this for something else in the future (which we shouldn't) and we want caching (which seems like a bad idea), we should explicitly turn it on and have to justify doing so.

Remove caching path for image build task

---

kubernetes/outreach.libsonnet

Testing this with the EKS pattern with a vault.jsonnet
Command:
```
kubecfg show addons/vault/vault.jsonnet \
-V cluster_name=cor-test2 \
-V cluster_region=us-east-2 \
-V cluster_environment=test \
-V cluster_fqdn=cor-test2.us-east-2.aws.outreach.cloud \
-V cluster_dns_zone=cor.outreach.cloud \
-V cluster_cloud_provider=aws
```
Returns: 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
annotations:
external-dns.alpha.kubernetes.io/target: contour.test.us-east-2.outreach.cloud
kubernetes.io/ingress.class: contour
labels:
app: vault-a-tls
name: vault-a
name: vault-a
namespace: vault
spec:
rules:
- host: vault-a.test.us-east-2.outreach.cloud
http:
paths:
- backend:
serviceName: vault-a
servicePort: http
```
And with a vault.jsonnet utilizing the clusters.yaml
Command:
```
kubecfg …
```

update ContourIngress to work with EKS

---

kubernetes/database-credentials.libsonnet

Example:
```
❯ kubecfg --jurl http://k8s-clusters.outreach.cloud/  --jurl file:///Users/davidboon/Projects/jsonnet-libs/ show online-schema-change-coordinator.database_user.jsonnet
---
apiVersion: databases.outreach.io/v1
kind: DatabaseCredential
metadata:
annotations: {}
labels:
app: test
name: test
name: test
spec:
grants:
- pattern: '*.*'
privilege: REPLICATION CLIENT, REPLICATION SLAVE, PROCESS
username: this_is_a_username
```

added databsae credential objects

---

LICENSE

**What this PR does**: Given this repository is Open Source and soon to be used by the devenv when it's open sourced, we should really have a license on this repository. Outreach uses/endorses Apache-2.0, and upstream [kube-libsonnet](https://github.com/bitnami-labs/kube-libsonnet/blob/master/kube.libsonnet) does as well, so we're able to use that with no issues.

docs: add a LICENSE

---

kubernetes/database-credentials.libsonnet

this change makes it easier to skip grants that might be otherwise hidden in a string, and skipping one embedded privilege is more difficult programmatically

QSS-720 making privileges an array

---

concourse/templates.libsonnet

**What this PR does**: per discussion with opslevel team, we need to append the env (production) to make sure build counts towards last deployed.
I am testing this PR with bootstraptestservice

fix(opslevel): add env to deploy func

---

kubernetes/kube.libsonnet

made all vaultSecret CRD pre-sync so secrets are populated when pods are deployed

fix: added vault secret ad pre-sync hook

---

kubernetes/kube.libsonnet

> Ingress resources are now available via networking.k8s.io/v1beta1. Ingress resources in extensions/v1beta1 are deprecated and will no longer be served in v1.18. Existing persisted data is available via the new API group/version 
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md#deprecations

feat: update ingress api version

---

kubernetes/database.libsonnet

This is part of QSS-813. The PR adds a new function to help wait for the database to provision, .i.e the CR to be ready. The main use case here is for devs to wait for this step in their concourse pipeline after calling $.PostgresqlDatabaseCluster (which only creates the CR, the dpo will reconcile and then mark the CR as ready once its created on AWS). By waiting, we ensure that when the go service consuming the db starts up, the database is actually provisioned and ready.

Adding a new function to help wait for db provisioning

---

concourse/resources.libsonnet
kubernetes/database.libsonnet

Making sure kubeconfig gets passed into the wait step containers. Also adding a timeout of 30 min for db provisioning(normally takes 15-20 min for provisioning to complete).
[QSS-813]
[QSS-813]: https://outreach-io.atlassian.net/browse/QSS-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Make sure kubeconfig gets passed in for WaitForDatabaseProvisioning

---

kubernetes/database.libsonnet

adds PostgresqlSharedDevenvDatabase that simplifies use of the DPO's PostgresqlDatabaseCluster operator with devenv shared db provisioner.
[QSS-825]
Tested in devenv by overriding local .bootstrap/shell/deploy-to-dev.sh script to this branch.
[QSS-825]: https://outreach-io.atlassian.net/browse/QSS-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[QSS-826]: https://outreach-io.atlassian.net/browse/QSS-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(database): add PostgresqlSharedDevenvDatabase

---

kubernetes/cluster.libsonnet

NGB needs the global_name as "{cluster_name}.{region}" but KOPS does need "{environment}.{region}". so we are introducing a new var "stub_name" which is defined in S3 for NGB 
https://github.com/getoutreach/ngb-terraform-modules/commit/f4e67892565d52ea1d10db4b2979f75ed83fc0c2

fix: use stub_name as global_name for ngb

---

kubernetes/kube.libsonnet

Putting the VaultSecret as a negative sync-wave will cause all VaultSecret objects to be deployed before anything else. 
This should work until we can patch the vault-secret-operator and have a status showing that the hook completed.

chore(VaultSecret): change from hook to sync-wave

---

kubernetes/outreach.libsonnet

contour.heptio.com is a deprecated annotation as of contour 1.0.0.

chore: update contour annotation

---

kubernetes/database.libsonnet

we added temp_builtin_users to PostgresqlDatabaseCluster CRD in https://github.com/getoutreach/database-provisioning-operator/pull/86, this PR enables callers to pass it thru.
PR verified in devenv.

feat(database): add temp_builtin_users to PostgreSQL

---

kubernetes/outreach.libsonnet

On the tin. 1.0.0+ deprecates the contour.heptio.com in favor of projectcontour.io

feat: update contour ingress annotation

---

kubernetes/discovery.libsonnet

**What this PR does**: This PR adds a new `discovery.libsonnet` that can be used to talk to [discovery](https://github.com/getoutreach/discovery) in our jsonnet files to get information about a given bento/channel at runtime.
**Depends on**: https://github.com/getoutreach/discovery/pull/41

feat(discovery): add discovery client

---

kubernetes/kube.libsonnet

change the hook from PreSync to Sync for jobs as some jobs requires secrets from Vault which is pulled in Sync mode with Wave -5.

fix: change argocd hook for job

---

kubernetes/argo.libsonnet

default true for report_maestro_ and report_opslevel_  as most of the cases are non-bootstrap apps which are required to report deployment status to maestro and opslevel.

fix(argocd): option to report maestro and opslevel

---

kubernetes/database.libsonnet

There are services that rely on DPO-generated VaultSecret during deployment (for legacy workflows). Because vault-secret-operator is invoked in wave-5, we need DPO's CR to be created beforehand to ensure vault secret is created to unblock VSO.

fix: create DPO CR before VSO

---

kubernetes/kube.libsonnet

default sync wave to configmap to be generated after vaultsecret and before job

chore: assign default sync wave to configmap

---

kubernetes/app.libsonnet

Legacy currently does not have 'type' key - https://s3.console.aws.amazon.com/s3/buckets/k8s-clusters.outreach.cloud?region=us-west-2
NGB has 'type' key - https://s3.console.aws.amazon.com/s3/buckets/outreach-eks-cluster-info-store?region=us-west-2&tab=objects

feat: add clusterType to app

---

kubernetes/outreach.libsonnet

While the default is `0`, aws-load-balancer-controller errors and states the explicit value must be between 1 and 1000.

fix: alb ingress ssl explicit group order needs to be higher than 0

---

kubernetes/outreach.libsonnet

I think it's helpful to not worry about redirects when the healthcheck defaults to `/`. That should just signal it's healthy.

feat: update healthcheck on ALB target groups

---

kubernetes/outreach.libsonnet

Having duplicate SSL redirection rules on ingresses does not seem to have a negative impact and serves to preserve the redirection correctly.

fix: default to having ssl redirection on all ingresses

---

kubernetes/outreach.libsonnet

When a cluster wide ALB is used across namespaces and applications these tags conflict and cannot be used.

fix: remove conflicting ALB tags when clusterALB is used

---

kubernetes/kube.libsonnet

Not urgent, just nice-to-have.  I'd appreciate your consideration of this patch @getoutreach/fnd-cors.  Thank you!
---
See https://github.com/kubernetes/kubernetes/issues/78570 for rationale.
tl;dr if your container crashes you can see the final logs emitted by your process in `kubectl describe pod`
[I searched through org code](https://cs.github.com/?q=org%3Agetoutreach+%22%2Fdev%2Ftermination-log%22&p=1&pt=39f00a08c2ce45d8addd4f45005995a5a78fc1fb28fe282801639be6d4072bca1da339e8ac83571ef41801e71afefa0958dac64716a9cb12c43ddcecb22a9bbc2a321e5fbca978e2e1bf24f1ed6646def08c756f73145cbdfc7740e2&scope=&scopeName=All+repos) for writes to "/dev/termination-log" to see if we have any libraries that handle this for us via the default mechanism, but didn't see any.

Set terminationMessagePolicy=FallbackToLogsOnError

---

kubernetes/outreach.libsonnet

As the PR title suggests, there are times we need/want to group ingresses in ways that are not based on the hostname and are also not a cluster shared ALB.

feat: enable custom grouping in ALB ingresses

---

kubernetes/outreach.libsonnet

Missed removing this in the last PR to update ssl-redirect functionality.

fix: remove unneeded alb annotation

---

kubernetes/argo.libsonnet

This issue happens only with applications that created from *-channel apps that have selfheal=true
1. *-channel apps was synced from github and it was trying to add selfheal=false and revert also image tag (VERSION) to original value which is empty as defined in https://github.com/getoutreach/applications (expected behavior)
2. maestro-updater patched application version with the correct versions from Maestro thru Kubernates API
3. ArgoCD detected that changes from step2 and patched ArgoCD applications and wiped off selfheal=false (ref: https://github.com/argoproj/argo-cd/blob/c702693380558c9fa06ddf4dee60484ab65138fc/pkg/apis/application/v1alpha1/types.go#L775)
4. a loop occur started here, ArgoCD repeats from step 1 again.

fix: remove argocd selfheal

---

concourse/resources.libsonnet

Follow up to https://github.com/getoutreach/jsonnet-libs/pull/192
**What this PR does**: This PR fixes issues like [this](https://concourse.outreach.cloud/teams/devs/pipelines/searchreindexservice/jobs/Deploy%20app1d/builds/58):
```bash
selected worker: worker-8
error: pathspec 'v1.105.0' did not match any file(s) known to git
```

fix(concourse/source): fetch_tags true

---

kubernetes/database.libsonnet

std.objectHas doesn't actually validate if hidden fields are present or not. This fixes it so that we properly assign the jsonnet. 
```
mukund.kidambi@C02FN542MD6R database-credential-operator %  kubecfg --jpath ../jsonnet-libs  --jurl http://k8s-clusters.outreach.cloud/ show -V "cluster=staging.us-east-2" -V "namespace=staging1a" -V "version=v1.5.0" manifests/onlineschemachange.databasecredential.jsonnet
---
apiVersion: databases.outreach.io/v1
kind: DatabaseCredential
metadata:
annotations: {}
labels:
app: flagship
name: onlineschemachange2
name: onlineschemachange2
namespace: staging1a
spec:
grants:
- pattern: '*.*'
privileges:
- REPLICATION CLIENT
- REPLICATION SLAVE
- PROCESS
- pattern: outreach_%
privileges:
- ALL
iamauth: false
username: onlineschemachange2
vault:
passwordKey: …
```

fix: Updating a minor bug in jsonnet-libs

---

kubernetes/database.libsonnet

Update name and type of `auth` spec, this will allow us to extend the authentication methods in the future. Also it makes more sense what this spec means. Default will be set to `mysql` for mysql native password.

fix: update spec for auth field

---

kubernetes/outreach.libsonnet

The AWS default idle_timeout is 60s, and this preserves that default.

feat: adjustable idle timeout on albs

---

kubernetes/kube.libsonnet

Changing `app` label on `kube-state-metrics` to `k8s-app` to avoid conflicts with deployment label `app` scraped with KSM & kubernetes_state DD integration -> basically avoiding this: https://github.com/DataDog/datadog-agent/issues/2671

fix(ksm): label app -> k8s-app COR-5785

---

kubernetes/argo.libsonnet

https://outreach-io.atlassian.net/browse/DT-2917
EXAMPLE
```
canary: rollouts.CanaryDeployment(app.name, app.version, app.namespace) {
deploymentRef:: $.deployment,
previewService:: $.alb_service_preview,
stableService:: $.alb_service,
ingress:: $.ingress,
servicePort:: 8080,
steps:: [
{ setWeight: 10 },
{ pause: { duration: '5m' } },
{ setWeight: 30 },
{ pause: { duration: '5m' } },
{ setWeight: 50 },
{ pause: { duration: '5m' } },
{ setWeight: 70 },
{ pause: { duration: '5m' } },
{ setWeight: 100 },
],
backgroundAnalysis:: {
templates: [
rollouts.AnalysisTemplateRef($.analysisMetric),
rollouts.AnalysisTemplateRef($.analysisWeb),
],
startingStep: 2,
},
metadata+: {
labels+: sharedLabels,
},
spec+: {
replicas: if isDev then 1 else 2,
},
},
analysisWeb: …
```

feat: add argo rollouts and analysis template

---

concourse/helpers.libsonnet

**What this PR does**: This PR removes `app1c` from the `appBentos` helper to ensure pipelines don't automatically get it (legacy pipelines that use this function, that is)

fix(helpers): remove app1c from appBentos

---

kubernetes/argo.libsonnet

enable notifications for Argo Rollouts which users can subscribe for success and/or failure events
https://outreach-io.atlassian.net/browse/DT-2916
relate to https://github.com/getoutreach/argo-rollouts/pull/5

feat: enable notifications for Argo Rollouts

---

kubernetes/argo.libsonnet

make ingress optional for Canary Deployment to support applications that do not have ingresses but want to deploy gradually with some tests

fix(canary): make ingress optional for CanaryDeployment

---

kubernetes/kube.libsonnet
kubernetes/outreach.libsonnet

test.jsonnet -> contains old `v1beta` and new `v1` APIs
```
#local ok = import 'kubernetes/kube.libsonnet';
local ok = import 'kubernetes/outreach.libsonnet';
local app = {
name: "alb-test",
namespace: "default",
host: "exampletest"
};
local all = {
// Application Load Balancer Ingresses
old_ingress: ok.ALBIngress(
name=app.name + '-old',
namespace=app.namespace,
serviceName=app.name,
servicePort='http',
createTls=true,
idleTimeoutSeconds='120',
) {
host:: app.host,  // <bento>-gazelle.outreach.cloud
},
new_ingress: ok.ALBIngressV1(
name=app.name + '-new',
namespace=app.namespace,
serviceName=app.name,
servicePort='http',
createTls=true,
idleTimeoutSeconds='120',
) {
host:: app.host,  // <bento>-gazelle.outreach.cloud
},
oldCRD: ok.CRD("Old", "old.io", "v1beta1") {
spec+: {
versions: [
{ …
```

add funcs IngressV1 and ALBIngressV1 for k8s 1.22

---

kubernetes/kube.libsonnet

updates `ok.CRDv1()`, version is pretty essential, and required argument. 
Also updates the PodDisruptionBudget version

fix: version is a required argument, fix CRDv1

---

kubernetes/kube.libsonnet

This will enable creation of new storageclass for EBS CSI driver. For this to be used we need to have EBS CSI driver deployed everywhere first so keeping this as draft until then.
Currently it is deployed into stagings with this PR: https://github.com/getoutreach/ngbentos/pull/374

new storage class with EBS CSI

---

kubernetes/oauth2-proxy.libsonnet

Updates the port name to be shorter than 15 characters for both of these, and creates a v1 compatible ingressrule for oauth2proxy.

feat: IngressRuleV1 for oauth2proxy

---

kubernetes/kube.libsonnet

[COR-5864]
Because we have everywhere EKS 1.23, we can use HPA v2.
[COR-5864]: https://outreach-io.atlassian.net/browse/COR-5864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add hpa v2 func

---

kubernetes/kube.libsonnet

This should ensure that namespaces deploy before anything else.

feat: add sync-wave for namespaces

---

kubernetes/kube.libsonnet

From k8s 1.21 available API version `policy/v1` and `batch/v1`
`test.json` manifest
```
local ok = import 'kubernetes/outreach.libsonnet';
local name = 'cluster-autoscaler';
local namespace = 'kube-system';
local all() = {
pdb: ok.PodDisruptionBudget(name, namespace) { spec+: { maxUnavailable: '50%' } },
cronjob: ok.CronJob(name, namespace) {
spec+: {
concurrencyPolicy: 'Forbid',
// At "22:00" every day
// https://crontab.guru/#0_20_*_*_*
schedule: '0 22 * * *',
jobTemplate: {
spec: {
backoffLimit: 2,
activeDeadlineSeconds: 600,
template: {
spec: {
serviceAccountName: name,
restartPolicy: 'OnFailure',
containers: [
ok.Container(name) {
// From bitnami/kubectl:1.21
image: 'gcr.io/outreach-docker/kubectl:1.21', // Need a version of kubectl that has rollout restart available
command: …
```

feat: update-policy/v1beta1&batch/v1beta1-to-v1

---

kubernetes/outreach.libsonnet

Adds `outreach:application` tag to ingresses. This should get merged with tags from controller and possibly override this tag. I am curious what will be result of the merge but it could help us assigning resources to services.

feat: add application tag to ingress

---

.github/CODEOWNERS
kubernetes/app.libsonnet

The 'ts' extVar doesn't have much value and requires invocation of things like `date`. It's non-standard at Outreach. I propose we deprecate it and eventually remove the field.
Using the static value '1690825986' as the output of `date +%s` (one of the ways of generating it) of the deprecation time.

fix(app): deprecate the 'ts' extVar

---

kubernetes/oauth2-proxy.libsonnet

This PR is in response to an issue that I discovered when attempting to deploy `getoutreach/shedinja` on my local devenv. The error message was:
```
Error updating deployments shedinja--bento1a.shedinja: Deployment.apps "shedinja" is invalid: spec.template.spec.containers[2].ports[0].name: 
Invalid value: "http-oauth2-proxy": must be no more than 15 characters  app.name=shedinja app.type=bootstrap
ERRO[0021] failed to run: failed to deploy app: .: failed to deploy changes: exit status 1 
```
This PR fixes the issue by renaming `http-oauth2-proxy` to just `http-o2p` to fall under the 15 character limit

fix: rename o2p port name to meet char limit

---

kubernetes/oauth2-proxy.libsonnet

Updates the port name requirements to be `http-o2p` everywhere instead of `http-o2p` for the containerPort and `oauth2-proxy` for the service port.

fix(oauth2-proxy): consolidate port name

---

kubernetes/oauth2-proxy.libsonnet

Accidentally put `listenPort` instead of `listen_port`... we need CI for
this repo. Sigh.

fix(oauth2-proxy): typo in listen_port

---

kubernetes/outreach.libsonnet

Change ALB policy in staging1a to TLS1.3. This is required by google as we have weak cihpers on our ALBs.
More bentos will follow up after testing this.
I used `cluster.fqdn` in condition for cluster name because I can see this is used in tags: https://github.com/getoutreach/jsonnet-libs/pull/252/files#diff-eb2627e12e96c449f5fae4526428b864114ef1bffbe7de58918adeca8d68d0b3R236
The value that this get interpolated into can be seen in the screenshot

feat: TLS1.3 for staging2b

---

kubernetes/outreach.libsonnet

The policy we used here had 2 weak ciphers. Security found out from the 2 ciphers are not meeting Google's requirements so we have to remove them and use even stronger policy.
You can look them up here in the **TLS 1.3 security policies** table: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies

fix(COR-6219): stronger SSL policy

---

kubernetes/oauth2-proxy.libsonnet

Updates `oauth2-proxy` as well as sets `--pass-user-headers` to `true` to ensure that `X-Forwaded-Email` is always passed to upstream.

fix(oauth2-proxy): pass X-Forwarded-Email header and v7.5.1

---

kubernetes/kube.libsonnet

According to the docs:
>  When there are enough endpoints available in each zone, Topology Hints will be populated on EndpointSlices to allocate individual endpoints to specific zones, resulting in traffic being routed closer to where it originated from.
The goal for this is to minimize the amount of cross-az traffic.
Docs: https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/

feat: add topology aware hints for services

---

kubernetes/kube.libsonnet

To be used in [kube_bento](https://github.com/getoutreach/kube_bento/pull/1798) for configuring HPA resources

feat: add DatadogMetric resource support

---

kubernetes/kube.libsonnet

This PR adds `topologySpreadConstraints` and removes `affinity` which should do the same thing (but didn't because it's just not flexible enough).
This PR does not add `minDomains` because it's still in beta and should graduate to stable in 1.27 and we are not there yet.
**Condition**
There is if/else conditional to apply this only on staging1a. The if/else statement is written so previous behavior with affinities is in `else` clause. In case the `bento` variable interpolates in something wrong, it will always fallback to current behavior.
`bento` is part of all argoCD application (unlike some thing we have in EKS addon like `cluster_name` etc.). You should be able to open any app here and there should be `BENTO` in parametets: https://argocd.app4a.eu-west-1.outreach.cloud/applications/arg …

feat: topologySpreadConstraints

---

kubernetes/kube.libsonnet

_Reopening this PR as apps without `bento` should be mostly fixed._
This PR adds `topologySpreadConstraints` and removes `affinity` which should do the same thing (but didn't because it's just not flexible enough).
This PR does not add `minDomains` because it's still in beta and should graduate to stable in 1.27 and we are not there yet.
**Condition**
There is if/else conditional to apply this only on staging1a. The if/else statement is written so previous behavior with affinities is in `else` clause. In case the `bento` variable interpolates in something wrong, it will always fallback to current behavior.
`bento` is part of all argoCD application (unlike some thing we have in EKS addon like `cluster_name` etc.). You should be able to open any app here and there should be `BENTO` in …

Topology spread constraints

---

kubernetes/outreach.libsonnet

On the tin.
Adds the following annotation:
```
'alb.ingress.kubernetes.io/target-type': 'ip',
```
Any other changes are from `jsonnetfmt` running.

feat: set target-type for ALBs to ip

---

kubernetes/outreach.libsonnet

Reverts getoutreach/jsonnet-libs#266
Errors from apiproxy:
```
ingress: apiproxy--staging1a/apiproxy-alb: cannot use named healthCheckPort for IP TargetType when service's targetPort is a named port
```
This looks like it needs to be reconfigured on each service.

Revert "feat: set target-type for ALBs to ip"

---

kubernetes/kube.libsonnet

Reverts getoutreach/jsonnet-libs#271
All apps except `flagship` were ok. However flagship remained in `Unknown` state where we couldn't keep it. We have to look into the error but revert this in the meantime
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `/bin/sh -c "argocd-maestro-plugin get-variable --channel \"$ARGOCD_MAESTRO_PLUGIN_CHANNEL\" --bento \"$ARGOCD_MAESTRO_PLUGIN_BENTO\" --application $ARGOCD_APP_NAME | xargs kubecfg --jurl https://raw.githubusercontent.com/getoutreach/jsonnet-libs/master --jpath /opt/jsonnet-libs show $(argocd-maestro-plugin …
```

Revert "Topology spread constraints"

---

kubernetes/kube.libsonnet

`maxSkew` of `1` means there cannot be bigger difference between 2 nodes running the same deployment than 1. In other words one host cannot run 2 pods while other has 0.
Changing this to `2` does allow bigger difference.
Main reason for this change is that karpenter treats this as hard requirement even with `ScheduleAnyway` and will not drain nodes which would violate this.
We can later discuss if we want to have this still `1` in production or if `2` is enough for us even there but in staging we can go with 2 or even more because it allows karpenter to consolidate nodes better.

feat: maxSkew increase for hostname

---

kubernetes/kube.libsonnet

Moves what we had on staging to production. All deployments will go out of sync and we will not sync them all to prevent syncing unwanted to prod. We might do automated sync after some time to finish what was left.
I plan to merge this tomorrow morning 09:00 - 10:00 CEST (00:00 - 01:00 PST).
Verified `kubecfg` manifest from this branch on coredns.

feat: topologySpreadConstraints on production

---

kubernetes/kube.libsonnet

This removed `topologySpreadConstraints` for `kubernetes.io/hostname` and return affinity for the same label.
We are changing this part back because we saw many new and small nodes coming from this previous change. `topologySpreadConstraints` with `maxSkew` caused karpenter to prepare small nodes and k8s then spread all pods from single deployment across all of them.
In the end this would mean additional cost because we have a lot bigger overhead from daemonsets now. It is also causing problems for karpenter during scaleups as it gets ratelimited by AWS because it tries to create many small instances.
Our clusters started scaling up on big number of very small nodes to satisfy the `topologySpreadConstraints` constraint.
Cluster node count in past 48 hours
Adds
Removes

feat: affinity for hostname

---

kubernetes/kube.libsonnet

We are still seeing high amount of tiny nodes. We will remove this in staging. The goal is to see bigger nodes. If we see this is causing too many pods of single deployment on one node, we will return to `topologySpreadConstraints` on `hostname` with higher `maxSkew` but removing this first and then potentially going back looks to be simpler approach then trying to tune `maxSkew` for the sweetspot.

feat(staging): no antiaffinity for hostname

---

kubernetes/kube.libsonnet

Removes affinity for hostname completely - we are not able to achieve good binpacking when karpenter tries to schedule each pod on different node.
**To be merged on monday Prague morning.**

feat: remove hostanme affinity on prod

---

.circleci/config.yml
Makefile
README.md
kubernetes/database.libsonnet
scripts/test.sh
tests/database.jsonnet
tests/database.snap

Add a libsonnet function for rendering PostgresqlClusterServiceAssignment resources. Add a way to define and run tests.
I can't test out the CI config until after this is merged. I'll fix any issues that may occur once this is in.
QSS-2346

feat(database): add PostgresqlClusterServiceAssignment

---

kubernetes/argo.libsonnet

[COR-5755](https://outreach-io.atlassian.net/browse/COR-5755)
This PR is to add two minutes delay to the argocd failure cases
[COR-5755]: https://outreach-io.atlassian.net/browse/COR-5755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

COR-5755-argocd-notifications

---

kubernetes/app.libsonnet

- Since we live in a NGB world now, we should set the default to NGB for cluster type.

fix: set default cluster type to NGB

---

kubernetes/kube.libsonnet

Removed in 1.22
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#apiservice-v122

chore: remove v1beta1 apiregistration

---

kubernetes/database.libsonnet

null for now, will eventually be removed
This change should be safe, any calls that provide the value will be respected, when to provided, temp_builtin_users will be pruned.

fix: temp_builtin_users was never needed/used

---

kubernetes/oauth2-proxy.libsonnet

Increase the CPU limit from 10m to 300m to prevent CPU starvation.
I noticed that request latency to Dash increased with concurrency. I tested this with a bash script and reproduced the issue. I suspected some bottleneck in the oauth2-proxy since the traces indicated that downstream requests (maestro and promototron) were completing much faster. I tested this manually and saw great improvements in page load time and reduced network latency.
The following before/after shows a set of parallel requests before and after the change to increase the cpu limit.
Before (~1s):
After (~80ms):

fix(oauth2-proxy): increase cpu limit

---

kubernetes/kube.libsonnet

Before
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
annotations: {}
labels:
istio.io/waypoint-for: all
name: server-internal-waypoint
reporting_team: fnd-pc
name: server-internal-waypoint
namespace: staging1a
spec:
gatewayClassName: istio-waypoint
infrastructure:
parametersRef:
group: ""
kind: ConfigMap
name: waypoint-config
listeners:
- name: mesh
port: 15008
protocol: HBONE
---
apiVersion: v1
data:
deployment: |-
"spec":
"template":
"spec":
"nodeSelector":
"outreach.io/nodepool": "ondemand"
"priorityClassName": "system-cluster-critical"
"tolerations":
- "effect": "NoSchedule"
"key": "dedicated"
"operator": "Equal"
"value": "ondemand"
kind: ConfigMap
metadata:
annotations:
argocd.argoproj.io/sync-wave: "-4"
labels:
app: fnd-pc
name: waypoint-config
reporting_team: …
```

fix: waypoint configmap name

---

kubernetes/kube.libsonnet

Add default sane configuration for all waypoints. This configuration assumes:
- at least 2 replicas (max 6 for now)
- PDB with maxUnavailable 1
- TSC with zone topology key
- always on `ondemand` nodes
- HPA with 80% CPU (we might need to tune this later)
- `system-cluster-critical` priority class
If waypoint doesn't do anything it will run as two replicas and scaleops should modify it to really low resources but we need to have them ready to handle more load. Staging1a list:

feat: waypoint pdb and hpa

---

kubernetes/kube.libsonnet

We don't want to have many small waypoints but rather bigger one that don't scale that often. Also looks like currently scaleops doesn't optimize waypoint (because they are owned by Gateway which is not supported) so we can't rely on scaleops bumping resources up.

feat: waypoint default sizing
