kubernetes/kube.libsonnet
kubernetes/outreach.libsonnet

* fix PodSpec.containers_ and PodSpec.initContainers_
* add namespace and app label to HPA
* fix statefulset and add namespace + app label
* add LimitRange and PDB types
* add private host field to ingress

various kubernetes fixes

---

concourse/templates.libsonnet

https://outreach-io.atlassian.net/browse/PLAT-1228
followup to: https://github.com/getoutreach/k8s-deploy-resource/pull/25

PLAT-1228 Add validation retries parameters

---

concourse/templates.libsonnet

I've seen vault fail to fetch secrets on various pipelines. It causes the whole job to halt in its tracks. These steps should attempt to retry in the face of network issues.

PLAT-1229 Attempt multiple times on commonly failed steps

---

kubernetes/kube.libsonnet

Also add some affinity rules for statefulsets

Allow eviction of pods

---

concourse/resources.libsonnet
concourse/templates.libsonnet

* Speed up pipeline by downloading images without docker
* Speed up builds by using the concourse builder image

Migrate to registry-image and concourse builder

---

concourse/templates.libsonnet

Backwards compatibility change required

fix build args

---

concourse/pipeline.libsonnet

Sublime also automatically cleaned up some trailing whitespace.

DEVTOOL-93: fix missing comma

---

concourse/helpers.libsonnet
concourse/pipeline.libsonnet
concourse/templates.libsonnet

Testing jsonnet is hard.
Actually include the helpers objects and make them functions so they don't interfere with the regular output.

Include helpers, make hidden functions

---

concourse/helpers.libsonnet

See subject.  Based on feedback from the `noggin-kafka` project.  Trying to keep this information generic, but this seems like it could be a useful add.

Add environment to bentos helper

---

concourse/helpers.libsonnet

[DSC-3553](https://outreach-io.atlassian.net/browse/DSC-3553)
Adds aws region to appBentos

[DSC-3553]Add AWS Region to appBentos

---

concourse/resources.libsonnet

Add resource type for the new maestro v2 resource

---

concourse/helpers.libsonnet

DEVTOOL-133: Remove red and amber channels from helpers function

---

concourse/resources.libsonnet

We are going for the hattrick now. I promise to delete the other 2 old versions once we are migrated 😆

Add latest maestro resource type to libraries

---

kubernetes/argo.libsonnet

All sensors seem to be fine using this image, so adding it to the libraries.

Update to new sensor image

---

concourse/templates.libsonnet

copied from Maestro's pipeline

add: maestro resource template function

---

concourse/helpers.libsonnet

add ops cluster in new non-application array

fix typo in cluster name

---

concourse/helpers.libsonnet

fixed typo

---

kubernetes/kube.libsonnet

**What this PR does**: This introduces `ok.FilteredList()` to filter out null values.

feat(kube): add a FilteredList() filters out null values in array

---

kubernetes/kube.libsonnet

Function for the operator described here: https://github.com/getoutreach/vault-secret-operator/blob/docs/README.md

Add vaultsecret

---

concourse/helpers.libsonnet

We have some pipelines using this, so let's make it correct.

Move app1e to green

---

kubernetes/argo.libsonnet

refactor: webhook port

---

kubernetes/argo.libsonnet

This reverts commit 46d1900b9aafb80ebc244ec5deb3a5901cefdc22.

Revert "refactor: webhook port"

---

kubernetes/kube.libsonnet

**What this PR does**: Adds a small helper for the gobox `cfg.SecretData` type

feat(kube): add GoSecretData helper

---

concourse/templates.libsonnet

**What this PR does**: sends deploy info to OpsLevel (method to be used upon successful deploy)
https://outreach-io.atlassian.net/browse/DTSS-476 
This PR has been tested with bootstraptestservice, please see https://concourse.outreach.cloud/teams/devs/pipelines/bootstraptestservice/jobs/Deploy%20staging1a/builds/2.8 as an example run

feat(opslevel): send deploy msg

---

concourse/templates.libsonnet

**What this PR does**: env var wrong in prev PR

fix(nissimn): fix env var name

---

kubernetes/argo.libsonnet

Added argo application jsonnet

feat: added applications to argo

---

kubernetes/database.libsonnet

$.basicResources was not defined as it is in the concourse folder. Redefining the definition here for the database.jsonnet to render. Avoiding import, as it would create a dep chain between /concourse and /kubernetes

fix: Minor fix for WaitForDatabaseProvisioning

---

kubernetes/database.libsonnet

Per Jared's comment, removing devenv method and adding provisioner to existing one so that we can override it.
[QSS-825]
Tested in devenv by overriding local .bootstrap/shell/deploy-to-dev.sh script to this branch.
[QSS-825]: https://outreach-io.atlassian.net/browse/QSS-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(database): merge operator functions

---

kubernetes/database.libsonnet

Adding env param so that we can extract most of the default postgreSQL spec values in jsonnet.
[QSS-825]
Tested in devenv by overriding local .bootstrap/shell/deploy-to-dev.sh script to this branch.
[QSS-825]: https://outreach-io.atlassian.net/browse/QSS-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(database): add env to derive postgresql defaults

---

kubernetes/argo.libsonnet

move the template from https://github.com/getoutreach/applications/blob/main/argoCD.libsonnet to the common repo.

fix: update argo app template

---

kubernetes/database.libsonnet

[QSS-841]
[QSS-841]: https://outreach-io.atlassian.net/browse/QSS-841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(database): Support specifying cluster parameters

---

kubernetes/database.libsonnet

fix: Minor typo in jsonnet lib

---

kubernetes/argo.libsonnet

add Argo AppProject and ApplicationSet and format code

feat: add Argo AppProject and ApplicationSet

---

concourse/helpers.libsonnet

Adds staging1c to the helpers.libsonnet

feat: add staging1c to helpers

---

kubernetes/app.libsonnet

fix(app): don't shadow std

---

kubernetes/app.libsonnet

feat: providing region in app object

---

kubernetes/outreach.libsonnet

fix: alb ingress ssl redirect

---

kubernetes/outreach.libsonnet

I want to be able to see how much ALB ingresses cost in AWS and this tag will help

feat: cost attribution tag

---

kubernetes/outreach.libsonnet

Reverts getoutreach/jsonnet-libs#185

Revert "fix: remove unneeded alb annotation"

---

kubernetes/argo.libsonnet

Options changed:
- Enabled prune
- Removed `CreateNamespace=true`
- Enabled `PruneLast=true`
- Enabled `selfHeal`
- Set `ApplyOutOfSyncOnly` to false

fix: tonymbugua/adjust-argocd-options

---

concourse/helpers.libsonnet

chore: remove app2d

---

kubernetes/database.libsonnet

this will allow manifest files to have either vault or iamauth set, previously vault was a required field.

feat: add iamauth as a field in spec

---

kubernetes/database.libsonnet

previous PR had unsupported syntax

fix: std.get is not supported, use std.objectHas

---

kubernetes/outreach.libsonnet

feat: tls 1.2 on ALBs

---

concourse/helpers.libsonnet

Missed as part of the NGB migration

fix(helpers): remove some bentos (legacy -> NGB)

---

kubernetes/argo.libsonnet

[DT-3428]
[DT-3428]: https://outreach-io.atlassian.net/browse/DT-3428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: disable argocd application selfheal

---

concourse/helpers.libsonnet

fix(helpers): remove all bentos

---

kubernetes/outreach.libsonnet

Makes the error clearer so we get less support requests around this.

fix: add string check for servicePort in alb ingress

---

kubernetes/database.libsonnet

[QSS-1851]
[QSS-1851]: https://outreach-io.atlassian.net/browse/QSS-1851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Missing ops env check

---

kubernetes/database.libsonnet

Adds a missing trailing comma which is causing jsonnet compilation errors.

fix: add missing trailing comma

---

kubernetes/database.libsonnet

adds default values for serverless scaling config
Need to merge https://github.com/getoutreach/database-provisioning-operator/pull/219 first

feat: add serverless scaling config field

---

kubernetes/database.libsonnet

need to come back and make serverless optional

fix: remove serverless for now

---

kubernetes/database.libsonnet

sets `serverless_scaling_config` default min max to rds clusters only.

feat: set serverless config for AuroraRDS clusters only

---

kubernetes/database.libsonnet

Reverts getoutreach/jsonnet-libs#239
it's causing issues 😭

Revert "feat: set serverless config for AuroraRDS clusters only"

---

kubernetes/database.libsonnet

also removes unused resources import
The addition of prune changes the output quite a bit. I'll be testing this in staging, pausing pipelines etc.

fix: add io_optimized_storage optional parameter

---

.github/CODEOWNERS

So we can merge our own PRs :D

chore: DT owns oauth2-proxy.libsonnet

---

kubernetes/oauth2-proxy.libsonnet

Reflects `listenPort` in `http-o2p` setting.

fix(oauth2-proxy): properly handle listenPort

---

kubernetes/outreach.libsonnet

Adding new SSL policy to all staging clusters

feat: new ssl policy on all staging albs

---

kubernetes/outreach.libsonnet

Enables stronger SSL policy on app1d

chore: stronger ciphers for app1d

---

kubernetes/outreach.libsonnet

Enables stronger SSL policy on `app1b`

chore: stronger ciphers for app1b

---

kubernetes/outreach.libsonnet

**Do not merge before Friday!**
This will push new TLS policy to all remaining ingresses using V1 function.

chore: tls 1.3 policy everywhere

---

kubernetes/kube.libsonnet

Reverts getoutreach/jsonnet-libs#267
Not everything rendered into yaml as expected. I have to fix that.

Revert "feat: topologySpreadConstraints"

---

kubernetes/kube.libsonnet

Reverts getoutreach/jsonnet-libs#269. Because of https://outreach-hq.slack.com/archives/CN9MU7GLW/p1707301271004719

Revert "Topology spread constraints"

---

kubernetes/kube.libsonnet

Reverts getoutreach/jsonnet-libs#277

Revert "feat: topologySpreadConstraints on production"

---

kubernetes/kube.libsonnet

Keeping affinites in devenv
details: https://outreach-hq.slack.com/archives/CN9MU7GLW/p1710242080001579

fix: devenv scheduling

---

.github/CODEOWNERS
kubernetes/database.libsonnet
tests/database.jsonnet
tests/database.snap

Add the new field `database_name` to the PostgresqlClusterServiceAssignment resource.
[QSS-2346]
[QSS-2346]: https://outreach-io.atlassian.net/browse/QSS-2346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(SharedClusters): add database_name to assignment resource

---

kubernetes/database.libsonnet
tests/database.jsonnet
tests/database.snap

Add resource_name to the PostgresqlClusterServiceAssignment.

feat(SharedClusters): add resource_name to service assignment

---

kubernetes/outreach.libsonnet

Reverts getoutreach/jsonnet-libs#222

Revert "feat: in ALBIngressV1 added ingressClassName with default 'alb'"

---

kubernetes/database.libsonnet

A github internal search shows this function not used

fix: remove unused function

---

kubernetes/kube.libsonnet

Creates waypoint proxy with
```
waypoint: ok.WaypointProxy(namespace=app.namespace),
```
Manifest generated is 
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
annotations: {}
labels:
istio.io/waypoint-for: service
name: waypoint
name: waypoint
namespace: org-fairness--staging1a
spec:
gatewayClassName: istio-waypoint
listeners:
- name: mesh
port: 15008
protocol: HBONE
```

Add waypoint

---

kubernetes/kube.libsonnet

Add more waypoint config so it's easier for teams to add it.
Example PR: https://github.com/getoutreach/mailroomapi/pull/486/files

Waypoint update

---

.circleci/config.yml
kubernetes/kube.libsonnet

Add istio kubernetes Gateway API config to the jsonnet-libs

add-gateway-api-config
